spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=${PORT}
jwt.secret=${JWT_SECRET}



jdbc:postgresql://url_db_1zhm_user:JZ8FKiVBuWZzbyTrtWjxz1gIvZFNz5Gg@dpg-d692ojh4tr6s73cf2cc0-a/url_db_1zhm